/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Modelos.CidadeEntrega;
import Modelos.Pedido;
import database.dao.PedidosDAO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LD-1196
 */
public class TelaAdministrador extends javax.swing.JDialog {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPrincipal = new javax.swing.JPanel();
        LblPrincipal = new javax.swing.JLabel();
        PnlBuscar = new javax.swing.JPanel();
        LblNome = new javax.swing.JLabel();
        LblCNH = new javax.swing.JLabel();
        TxtCodigoEntrega = new javax.swing.JTextField();
        TxtCNH = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        TblMotoristas = new javax.swing.JScrollPane();
        TblAdministrador = new javax.swing.JTable();
        BtnGerenciar = new javax.swing.JButton();
        BtnGerenciarCidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                AoAbrirJanela(evt);
            }
        });

        PnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        LblPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        LblPrincipal.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        LblPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        LblPrincipal.setText("Administrador");

        javax.swing.GroupLayout PnlPrincipalLayout = new javax.swing.GroupLayout(PnlPrincipal);
        PnlPrincipal.setLayout(PnlPrincipalLayout);
        PnlPrincipalLayout.setHorizontalGroup(
            PnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlPrincipalLayout.setVerticalGroup(
            PnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PnlBuscar.setBackground(new java.awt.Color(204, 204, 204));
        PnlBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Entrega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 1, 14))); // NOI18N
        PnlBuscar.setForeground(new java.awt.Color(153, 153, 153));

        LblNome.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblNome.setText("Codigo Entrega:");

        LblCNH.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblCNH.setText("CNH:");

        BtnBuscar.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        BtnBuscar.setText("Buscar");

        javax.swing.GroupLayout PnlBuscarLayout = new javax.swing.GroupLayout(PnlBuscar);
        PnlBuscar.setLayout(PnlBuscarLayout);
        PnlBuscarLayout.setHorizontalGroup(
            PnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblNome)
                    .addComponent(LblCNH))
                .addGap(29, 29, 29)
                .addGroup(PnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtCodigoEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(TxtCNH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(BtnBuscar)
                .addGap(22, 22, 22))
        );
        PnlBuscarLayout.setVerticalGroup(
            PnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBuscarLayout.createSequentialGroup()
                .addGroup(PnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNome)
                            .addComponent(TxtCodigoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(PnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCNH)
                            .addComponent(TxtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlBuscarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BtnBuscar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        TblAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CNH", "Nome Motorista", "Nome Cliente", "CPF Cliente", "Data Pedido", "Cidade Destino", "Cidade Atual", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblMotoristas.setViewportView(TblAdministrador);

        BtnGerenciar.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        BtnGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/administrator.png"))); // NOI18N
        BtnGerenciar.setText("Gerenciar Motoristas");
        BtnGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirGerenciarMotorista(evt);
            }
        });

        BtnGerenciarCidade.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        BtnGerenciarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/city.png"))); // NOI18N
        BtnGerenciarCidade.setText("Gerenciar Cidades");
        BtnGerenciarCidade.setMaximumSize(new java.awt.Dimension(207, 39));
        BtnGerenciarCidade.setMinimumSize(new java.awt.Dimension(207, 39));
        BtnGerenciarCidade.setPreferredSize(new java.awt.Dimension(207, 39));
        BtnGerenciarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirGerenciarCidades(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TblMotoristas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGerenciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGerenciarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TblMotoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGerenciar)
                    .addComponent(BtnGerenciarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirGerenciarMotorista(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirGerenciarMotorista
        
        TelaGerenciarMotorista tgm = new TelaGerenciarMotorista(null, true);
        tgm.setVisible(true);
    }//GEN-LAST:event_AbrirGerenciarMotorista

    private void AbrirGerenciarCidades(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirGerenciarCidades
        
        TelaGerenciarCidades tgc = new TelaGerenciarCidades(null, true);
        tgc.setVisible(true);
        
    }//GEN-LAST:event_AbrirGerenciarCidades

    private void AoAbrirJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AoAbrirJanela
        
        PreencherTable(true);
        
    }//GEN-LAST:event_AoAbrirJanela

    ArrayList<Pedido> lista;
    ArrayList<Pedido> lista2;
    
    public void PreencherTable(boolean todos) throws HeadlessException{
        
        try {
           // new PedidosDAO().BuscarTodos();
           // new PedidosDAO().BuscarPendentes();
            
            if(todos)
            {
                lista = new PedidosDAO().BuscarTodos();
                lista2 = new PedidosDAO().BuscarPendentes();
            }
            
            DefaultTableModel dftm = (DefaultTableModel) TblAdministrador.getModel();
            
            while(dftm.getRowCount() >= 1)
            {
                dftm.removeRow(dftm.getRowCount()-1);
            }
            
            for(Pedido p: lista)
            {
                String[] linha = {p.getMotorista().getCnh()+"",p.getMotorista().getNome(),p.getCliente().getNome(),p.getCliente().getCpf(),p.getDataPedido(),p.getCidade().getNome(),p.getCidadeAtual(),p.getStatus()};
                dftm.addRow(linha);
            }
            
            for(Pedido p: lista2)
            {
                if(p.getStatus().equalsIgnoreCase("Pendente"))
                {
                    String[] linha = {"Não Atribuido","Não Atribuido",p.getCliente().getNome(),p.getCliente().getCpf(),p.getDataPedido(),p.getCidade().getNome(),p.getCidadeAtual(),p.getStatus()};
                    dftm.addRow(linha);
                }
            }
            
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Erro ao salvar!"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Erro do Driver");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAdministrador dialog = new TelaAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnGerenciar;
    private javax.swing.JButton BtnGerenciarCidade;
    private javax.swing.JLabel LblCNH;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblPrincipal;
    private javax.swing.JPanel PnlBuscar;
    private javax.swing.JPanel PnlPrincipal;
    private javax.swing.JTable TblAdministrador;
    private javax.swing.JScrollPane TblMotoristas;
    private javax.swing.JTextField TxtCNH;
    private javax.swing.JTextField TxtCodigoEntrega;
    // End of variables declaration//GEN-END:variables
}
