/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Modelos.CidadeEntrega;
import Modelos.Cliente;
import Modelos.Motorista;
import Modelos.Pedido;
import database.dao.CidadeEntregaDAO;
import database.dao.ClienteDAO;
import database.dao.MotoristaDAO;
import database.dao.PedidosDAO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patricia
 */
public class TelaRegistroEntrega extends javax.swing.JDialog {
    
    private Pedido pedido;

    public TelaRegistroEntrega(Pedido pedido) {
        this.pedido = pedido;
    }

    public Pedido getPedido() {
        return pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    
    public String cnh;

    /**
     * Creates new form TelaRegistroEntrega
     */
    public TelaRegistroEntrega(java.awt.Frame parent, boolean modal, String cnh) {
        super(parent, modal);
        this.cnh = cnh;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPrincipal = new javax.swing.JPanel();
        LblPrincipal = new javax.swing.JLabel();
        LblCodigoEntrega = new javax.swing.JLabel();
        TxtCodigoEntrega = new javax.swing.JTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LblCidadeDestino = new javax.swing.JLabel();
        TxtCidadeDestino = new javax.swing.JTextField();
        LblCidadeAtual = new javax.swing.JLabel();
        LblDistancia = new javax.swing.JLabel();
        TxtDistancia = new javax.swing.JTextField();
        LblPrazo = new javax.swing.JLabel();
        TxtPrazo = new javax.swing.JTextField();
        CbCidadeAtual = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        LblCPFCliente = new javax.swing.JLabel();
        TxtCPFCliente = new javax.swing.JTextField();
        LblNomeCliente = new javax.swing.JLabel();
        TxtNomeCliente = new javax.swing.JTextField();
        LblEnderecoCliente = new javax.swing.JLabel();
        TxtEnderecoCliente = new javax.swing.JTextField();
        LblAniversario = new javax.swing.JLabel();
        TxtAniversario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        LblCarga = new javax.swing.JLabel();
        TxtCarga = new javax.swing.JTextField();
        LblStatus = new javax.swing.JLabel();
        TxtStatus = new javax.swing.JTextField();
        LblDescricao = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        LblValorEntrega = new javax.swing.JLabel();
        TxtValorEntrega = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtDataPedido = new javax.swing.JTextField();
        BtnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPedidos = new javax.swing.JTable();
        LblCNH = new javax.swing.JLabel();
        TxtCNH = new javax.swing.JTextField();
        BtnMinhasEntregas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                AoAbrirJanela(evt);
            }
        });

        PnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        LblPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        LblPrincipal.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        LblPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        LblPrincipal.setText("Nova Entrega");

        javax.swing.GroupLayout PnlPrincipalLayout = new javax.swing.GroupLayout(PnlPrincipal);
        PnlPrincipal.setLayout(PnlPrincipalLayout);
        PnlPrincipalLayout.setHorizontalGroup(
            PnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        PnlPrincipalLayout.setVerticalGroup(
            PnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LblCodigoEntrega.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblCodigoEntrega.setText("Codigo Entrega:");

        BtnSalvar.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh.png"))); // NOI18N
        BtnSalvar.setText("Atualizar Dados");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarPedido(evt);
            }
        });

        BtnCancelar.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharJanela(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Cidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 1, 12))); // NOI18N

        LblCidadeDestino.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblCidadeDestino.setText("Cidade Destino:");

        TxtCidadeDestino.setEnabled(false);

        LblCidadeAtual.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblCidadeAtual.setText("Cidade Atual:");

        LblDistancia.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblDistancia.setText("Distância:");

        TxtDistancia.setEnabled(false);

        LblPrazo.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblPrazo.setText("Prazo para Entrega:");

        TxtPrazo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblCidadeAtual)
                            .addComponent(LblDistancia)
                            .addComponent(LblCidadeDestino))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCidadeDestino)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 68, Short.MAX_VALUE))
                            .addComponent(CbCidadeAtual, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblPrazo)
                        .addGap(18, 18, 18)
                        .addComponent(TxtPrazo)))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCidadeDestino)
                    .addComponent(TxtCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCidadeAtual)
                    .addComponent(CbCidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDistancia)
                    .addComponent(TxtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPrazo)
                    .addComponent(TxtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 1, 12))); // NOI18N

        LblCPFCliente.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblCPFCliente.setText("CPF:");

        TxtCPFCliente.setEnabled(false);

        LblNomeCliente.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblNomeCliente.setText("Nome:");

        TxtNomeCliente.setEnabled(false);

        LblEnderecoCliente.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblEnderecoCliente.setText("Endereço:");

        TxtEnderecoCliente.setEnabled(false);

        LblAniversario.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblAniversario.setText("Aniversário:");

        TxtAniversario.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblCPFCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(LblEnderecoCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtEnderecoCliente)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LblAniversario)
                        .addGap(18, 18, 18)
                        .addComponent(TxtAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCPFCliente)
                    .addComponent(TxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNomeCliente)
                    .addComponent(TxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEnderecoCliente)
                    .addComponent(TxtEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAniversario)
                    .addComponent(TxtAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Entrega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 1, 12))); // NOI18N

        LblCarga.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblCarga.setText("Tipo de Carga:");

        TxtCarga.setEnabled(false);

        LblStatus.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblStatus.setText("Status Entrega:");

        TxtStatus.setEnabled(false);

        LblDescricao.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblDescricao.setText("Descrição:");

        TxtDescricao.setEnabled(false);

        LblValorEntrega.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblValorEntrega.setText("Valor Entrega:");

        TxtValorEntrega.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel1.setText("Data Pedido:");

        TxtDataPedido.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblCarga)
                    .addComponent(LblDescricao))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtCarga, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(TxtDescricao))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblStatus)
                    .addComponent(LblValorEntrega)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtDataPedido)
                    .addComponent(TxtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(TxtValorEntrega))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCarga)
                    .addComponent(TxtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblStatus)
                    .addComponent(TxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblDescricao)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblValorEntrega)
                            .addComponent(TxtValorEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(TxtDescricao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnPesquisar.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarPedido(evt);
            }
        });

        TblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Pedido", "Nome Cliente", "Cidade Destino", "Porte da Carga", "Status Entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblPedidos);

        LblCNH.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        LblCNH.setText("CNH:");

        TxtCNH.setEnabled(false);

        BtnMinhasEntregas.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        BtnMinhasEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/truck.png"))); // NOI18N
        BtnMinhasEntregas.setText("Minhas Entregas");
        BtnMinhasEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinhasEntregas(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblCodigoEntrega)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCodigoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BtnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblCNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnMinhasEntregas)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCNH)
                    .addComponent(TxtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMinhasEntregas))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCodigoEntrega)
                    .addComponent(TxtCodigoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AoAbrirJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AoAbrirJanela
        
        try {
            PreencherTable(true);
        } catch (HeadlessException ex) {
            Logger.getLogger(TelaRegistroEntrega.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaRegistroEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaLoginMotorista tlm = new TelaLoginMotorista(cnh);
        TxtCNH.setText(cnh);
        
    }//GEN-LAST:event_AoAbrirJanela

    private void PreencherCombo()
    {
        try {
            ArrayList<CidadeEntrega> lista = new CidadeEntregaDAO().BuscarTodos();
            
            DefaultComboBoxModel<String> dcbm = (DefaultComboBoxModel<String>) CbCidadeAtual.getModel();
            
            dcbm.removeAllElements();
            
            for(CidadeEntrega c: lista)
            {
                dcbm.addElement(c.getNome());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaRealizarPedido.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaRealizarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void PesquisarPedido(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarPedido
        
        Pedido p;
        
        try {
                p = new PedidosDAO().BuscarPendentePelaChave(Integer.parseInt(TxtCodigoEntrega.getText()));
                
                TxtCidadeDestino.setText(p.getCidade().getNome());
                PreencherCombo();
                TxtDistancia.setText(p.getCidade().getDistancia()+"");
                TxtPrazo.setText(p.getCidade().getTempoEntrega());
                
                TxtCPFCliente.setText(p.getCliente().getCpf());
                TxtNomeCliente.setText(p.getCliente().getNome());
                TxtEnderecoCliente.setText(p.getCliente().getEndereco());
                TxtAniversario.setText(p.getCliente().getDataNasc());
                
                TxtCarga.setText(p.getVeiculo());
                TxtStatus.setText(p.getStatus());
                TxtDescricao.setText(p.getDescricao());
                TxtValorEntrega.setText(p.getValorPedido()+"");
                TxtDataPedido.setText(p.getDataPedido());
                
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_PesquisarPedido

    private void FecharJanela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharJanela
        
        this.dispose();
        
    }//GEN-LAST:event_FecharJanela

    private void RealizarPedido(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarPedido
        
        Pedido pedido;
        
        try {
            
            Motorista m = new MotoristaDAO().BuscarCNH(TxtCNH.getText());
            
            if(CbCidadeAtual.getSelectedItem().toString().equalsIgnoreCase(TxtCidadeDestino.getText()))
            {
                pedido = new Pedido(0,TxtDescricao.getText(),CbCidadeAtual.getSelectedItem().toString(),TxtCarga.getText(),"Entregue",null,Double.parseDouble(TxtValorEntrega.getText()),null,null,m);
                m = new Motorista(m.getCnh(),m.getCategoria(),"Disponível",m.getId(),m.getNome(),m.getEndereco(),m.getSexo(),m.getDataNasc());
            }            
            else
            {
                pedido = new Pedido(0,TxtDescricao.getText(),CbCidadeAtual.getSelectedItem().toString(),TxtCarga.getText(),"A Caminho",null,Double.parseDouble(TxtValorEntrega.getText()),null,null,m);
                m = new Motorista(m.getCnh(),m.getCategoria(),"Não Disponível",m.getId(),m.getNome(),m.getEndereco(),m.getSexo(),m.getDataNasc());
            }
            
                ((Pedido)pedido).setId(Integer.parseInt(TxtCodigoEntrega.getText()));
                new PedidosDAO().Alterar((Pedido)pedido);
                ((Motorista)m).setId(m.getId());
                new MotoristaDAO().Alterar((Motorista)m);
            
            
            JOptionPane.showMessageDialog(null, "Entrega atribuida a CNH!");
            
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_RealizarPedido

    private void MinhasEntregas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinhasEntregas
        
        boolean todos = true;
        
        try {
            new PedidosDAO().BuscarPedidoCNH(TxtCNH.getText());
            
            if(todos)
            {
                lista = new PedidosDAO().BuscarPedidoCNH(TxtCNH.getText());
            }
            
            DefaultTableModel dftm = (DefaultTableModel) TblPedidos.getModel();
            
            while(dftm.getRowCount() >= 1)
            {
                dftm.removeRow(dftm.getRowCount()-1);
            }
            
            for(Pedido p: lista)
            {           
                if(p.getStatus().equalsIgnoreCase("A Caminho"))
                {
                    String[] linha = {p.getId()+"",p.getCliente().getNome(),p.getCidade().getNome(),p.getVeiculo(),p.getStatus()};
                    dftm.addRow(linha);
                }
            }
            
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Erro ao salvar!"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Erro do Driver");
        }
        
    }//GEN-LAST:event_MinhasEntregas

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRegistroEntrega dialog = new TelaRegistroEntrega(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    ArrayList<Pedido> lista;
    
    public void PreencherTable(boolean todos) throws HeadlessException, SQLException{
        
        try {
            new PedidosDAO().BuscarPendentes();
            
            if(todos)
            {
                lista = new PedidosDAO().BuscarPendentes();
            }
            
            DefaultTableModel dftm = (DefaultTableModel) TblPedidos.getModel();
            
            while(dftm.getRowCount() >= 1)
            {
                dftm.removeRow(dftm.getRowCount()-1);
            }
            
            for(Pedido p: lista)
            {
                if(p.getStatus().equalsIgnoreCase("Pendente"))
                {
                    String[] linha = {p.getId()+"",p.getCliente().getNome(),p.getCidade().getNome(),p.getVeiculo(),p.getStatus()};
                    dftm.addRow(linha);
                }
            }
            
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Erro ao salvar!"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Erro do Driver");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnMinhasEntregas;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JComboBox<String> CbCidadeAtual;
    private javax.swing.JLabel LblAniversario;
    private javax.swing.JLabel LblCNH;
    private javax.swing.JLabel LblCPFCliente;
    private javax.swing.JLabel LblCarga;
    private javax.swing.JLabel LblCidadeAtual;
    private javax.swing.JLabel LblCidadeDestino;
    private javax.swing.JLabel LblCodigoEntrega;
    private javax.swing.JLabel LblDescricao;
    private javax.swing.JLabel LblDistancia;
    private javax.swing.JLabel LblEnderecoCliente;
    private javax.swing.JLabel LblNomeCliente;
    private javax.swing.JLabel LblPrazo;
    private javax.swing.JLabel LblPrincipal;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JLabel LblValorEntrega;
    private javax.swing.JPanel PnlPrincipal;
    private javax.swing.JTable TblPedidos;
    private javax.swing.JTextField TxtAniversario;
    private javax.swing.JTextField TxtCNH;
    private javax.swing.JTextField TxtCPFCliente;
    private javax.swing.JTextField TxtCarga;
    private javax.swing.JTextField TxtCidadeDestino;
    private javax.swing.JTextField TxtCodigoEntrega;
    private javax.swing.JTextField TxtDataPedido;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JTextField TxtDistancia;
    private javax.swing.JTextField TxtEnderecoCliente;
    private javax.swing.JTextField TxtNomeCliente;
    private javax.swing.JTextField TxtPrazo;
    private javax.swing.JTextField TxtStatus;
    private javax.swing.JTextField TxtValorEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
